name: Replace README

on:
  workflow_dispatch:
    inputs:
      time:
        description: "time list"
        required: false

env:
  # change env here
  GITHUB_NAME: CodeMeditator
  GITHUB_EMAIL: richardchen.rayage@hotmail.com

jobs:
  sync:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip" # caching pip dependencies

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Replace README
        run: |
          python main.py $'${{ github.event.inputs.startTime }}' $'${{ github.event.inputs.endTime }}'

      - name: Push README
        run: |
          git config --local user.email "${{ env.GITHUB_EMAIL }}"
          git config --local user.name "${{ env.GITHUB_NAME }}"
          git commit -a -m 'update new sleep' || echo "nothing to commit"
          git push || echo "nothing to push"
